include:
    - project: vernok/gitlab-ci-templates
      file: /october-plugin-ci.yml

variables:
    PACKAGIST_PUBLISH: "true"
    PACKAGIST_REPOSITORY_URL: "https://github.com/hello-vernok/vite-plugin-october"
